-- Startdaten (im Admin-Bereich pflegbar)
insert into public.seasons (name, is_current) values ('Aktuelle Season', true);

insert into public.rules (text, category, weight) values
  ('Nur graue Waffen', 'rad', 2),
  ('Kein Bauen', 'rad', 2),
  ('Nur Heilung aus Fischen', 'rad', 1),
  ('Keine Schilde', 'rad', 1),
  ('Nur eine Waffe gleichzeitig', 'rad', 2),
  ('Kein Sprinten', 'rad', 1),
  ('Nur Pickaxe bis zum ersten Kill', 'rad', 1),
  ('Kein Fahrzeug', 'rad', 2),
  ('Nur Loot vom Boden', 'rad', 1),
  ('Erste Waffe muss behalten werden', 'rad', 2),
  ('Keine Kisten öffnen', 'rad', 1),
  ('Nur Scharfschützengewehre', 'rad', 1),
  ('Erst 3 Fische fangen, dann looten', 'drop', 1),
  ('Landen ohne Gleiter-Umweg (direkt runter)', 'drop', 2),
  ('Erste gefundene Waffe ist die einzige', 'drop', 2),
  ('Bis zur zweiten Zone im POI bleiben', 'drop', 1),
  ('Keine Heilung bis zum ersten Kill', 'drop', 1);

-- Lootpool der aktuellen Season (Quelle: supabase/loot/aktuelle-season.txt, im Admin per Import pflegbar)
insert into public.loot_items (name, rarity, type, description, season_id)
select v.name, v.rarity, v.type, v.description, (select id from public.seasons where is_current)
from (values
  ('Assault Rifle', 'grau', 'waffe', 'Allround-Gewehr für mittlere Distanz.'),
  ('Assault Rifle', 'gruen', 'waffe', 'Allround-Gewehr für mittlere Distanz.'),
  ('Assault Rifle', 'blau', 'waffe', 'Allround-Gewehr für mittlere Distanz.'),
  ('Assault Rifle', 'lila', 'waffe', 'Allround-Gewehr für mittlere Distanz.'),
  ('Assault Rifle', 'gold', 'waffe', 'Allround-Gewehr für mittlere Distanz.'),
  ('Heavy Assault Rifle', 'grau', 'waffe', 'Mehr Schaden pro Schuss, dafür stärkerer Rückstoß.'),
  ('Heavy Assault Rifle', 'gruen', 'waffe', 'Mehr Schaden pro Schuss, dafür stärkerer Rückstoß.'),
  ('Heavy Assault Rifle', 'blau', 'waffe', 'Mehr Schaden pro Schuss, dafür stärkerer Rückstoß.'),
  ('Heavy Assault Rifle', 'lila', 'waffe', 'Mehr Schaden pro Schuss, dafür stärkerer Rückstoß.'),
  ('Heavy Assault Rifle', 'gold', 'waffe', 'Mehr Schaden pro Schuss, dafür stärkerer Rückstoß.'),
  ('8-Bit Shotgun', 'grau', 'waffe', null),
  ('8-Bit Shotgun', 'gruen', 'waffe', null),
  ('8-Bit Shotgun', 'blau', 'waffe', null),
  ('8-Bit Shotgun', 'lila', 'waffe', null),
  ('8-Bit Shotgun', 'gold', 'waffe', null),
  ('Pump Shotgun', 'grau', 'waffe', 'Hoher Schaden auf kurze Distanz, langsames Nachladen.'),
  ('Pump Shotgun', 'gruen', 'waffe', 'Hoher Schaden auf kurze Distanz, langsames Nachladen.'),
  ('Pump Shotgun', 'blau', 'waffe', 'Hoher Schaden auf kurze Distanz, langsames Nachladen.'),
  ('Pump Shotgun', 'lila', 'waffe', 'Hoher Schaden auf kurze Distanz, langsames Nachladen.'),
  ('Pump Shotgun', 'gold', 'waffe', 'Hoher Schaden auf kurze Distanz, langsames Nachladen.'),
  ('Sweeper Shotgun', 'grau', 'waffe', null),
  ('Sweeper Shotgun', 'gruen', 'waffe', null),
  ('Sweeper Shotgun', 'blau', 'waffe', null),
  ('Sweeper Shotgun', 'lila', 'waffe', null),
  ('Sweeper Shotgun', 'gold', 'waffe', null),
  ('Wood Stake Shotgun', 'blau', 'waffe', null),
  ('Wood Stake Shotgun', 'lila', 'waffe', null),
  ('Wood Stake Shotgun', 'gold', 'waffe', null),
  ('Bonerattler SMG', 'gruen', 'waffe', null),
  ('Bonerattler SMG', 'blau', 'waffe', null),
  ('Bonerattler SMG', 'lila', 'waffe', null),
  ('Bonerattler SMG', 'gold', 'waffe', null),
  ('Tactical Pistol', 'grau', 'waffe', null),
  ('Tactical Pistol', 'gruen', 'waffe', null),
  ('Tactical Pistol', 'blau', 'waffe', null),
  ('Tactical Pistol', 'lila', 'waffe', null),
  ('Tactical Pistol', 'gold', 'waffe', null),
  ('Rebecca''s Guns', 'grau', 'waffe', null),
  ('Rebecca''s Guns', 'gruen', 'waffe', null),
  ('Rebecca''s Guns', 'blau', 'waffe', null),
  ('Rebecca''s Guns', 'lila', 'waffe', null),
  ('Rebecca''s Guns', 'gold', 'waffe', null),
  ('Mega Buster', 'blau', 'waffe', null),
  ('Firework Flare Gun', 'blau', 'waffe', null),
  ('Kingdom Key', 'lila', 'waffe', null),
  ('Dual Fiend Hunters', 'grau', 'waffe', null),
  ('Dual Fiend Hunters', 'gruen', 'waffe', null),
  ('Dual Fiend Hunters', 'blau', 'waffe', null),
  ('Dual Fiend Hunters', 'lila', 'waffe', null),
  ('Dual Fiend Hunters', 'gold', 'waffe', null),
  ('Bandages', 'grau', 'heilung', 'Heilt Leben in kleinen Schritten.'),
  ('Med Kit', 'gruen', 'heilung', 'Heilt Leben vollständig, braucht aber Zeit.'),
  ('Small Shield Potion', 'gruen', 'heilung', 'Kleiner Schild-Schub, schnell getrunken.'),
  ('Small Shield Potion', 'blau', 'heilung', 'Kleiner Schild-Schub, schnell getrunken.'),
  ('Shield Potion', 'blau', 'heilung', 'Großer Schild-Schub.'),
  ('Chug Jug', 'gold', 'heilung', 'Füllt Leben und Schild komplett auf – dauert aber.'),
  ('Quack Snacks', 'gold', 'heilung', null),
  ('Candy Corn', 'gruen', 'heilung', null),
  ('Jelly Bean', 'gruen', 'heilung', null),
  ('Hop Drop', 'gruen', 'heilung', null),
  ('Slap Candy Corn', 'blau', 'heilung', null),
  ('Sea Salt Ice Cream', 'blau', 'heilung', null),
  ('Sonic Power Sneakers', 'lila', 'utility', null),
  ('Witch Broom', 'lila', 'utility', null),
  ('Balloons', 'blau', 'utility', 'Lässt dich schweben und weit springen.'),
  ('Override Grenade', 'blau', 'utility', null),
  ('Snack-O''-Lantern Gizmo', 'gruen', 'utility', null),
  ('Brick-A-Bunker', 'grau', 'utility', null),
  ('Shield Bubble Jr.', 'gruen', 'utility', null),
  ('Bush', 'gold', 'utility', 'Tarnung als Busch.')
) as v(name, rarity, type, description);

insert into public.drop_spots (name, season_id, x, y)
select v.name, (select id from public.seasons where is_current), v.x, v.y
from (values
  ('Nordküste', 20, 15), ('Zentrum', 50, 50), ('Westwald', 15, 55),
  ('Ostberge', 82, 40), ('Südhafen', 55, 85), ('Insel im See', 40, 35),
  ('Wüstenstadt', 75, 75), ('Burg', 30, 80)
) as v(name, x, y);

insert into public.bingo_tasks (text) values
  ('Kill mit Pickaxe'), ('Top 10 ohne Schild'), ('Gold-Waffe finden'), ('Fisch fangen'),
  ('Kill aus Fahrzeug'), ('3 Kisten in Folge'), ('Kill mit grauer Waffe'), ('Sniper-Kill über 100 m'),
  ('Victory Royale'), ('Kill ohne zu bauen'), ('In der Zone sterben (fast)'), ('Mythische Waffe'),
  ('Revive eines Mitspielers'), ('Lama gefunden'), ('Kill mit Granate'), ('5 Kills'),
  ('Top 5'), ('Doppel-Kill'), ('Geschenk aus Kiste: Heilung'), ('Erste Landung überlebt'),
  ('Kill mit Raketenwerfer'), ('100 Schaden in einem Schuss'), ('Ohne Heilung Top 15'), ('Emote nach Kill'),
  ('Lagerfeuer genutzt'), ('Vom Bus als Letzter abspringen'), ('Kill aus der Luft'), ('Kill mit Pistole');
