-- Startdaten (im Admin-Bereich pflegbar)
insert into public.seasons (name, is_current) values ('Aktuelle Season', true);

insert into public.rules (text, category, weight) values
  ('Nur graue Waffen', 'rad', 2),
  ('Kein Bauen', 'rad', 2),
  ('Nur Heilung aus Fischen', 'rad', 1),
  ('Keine Schilde', 'rad', 1),
  ('Nur eine Waffe gleichzeitig', 'rad', 2),
  ('Kein Sprinten', 'rad', 1),
  ('Nur Pickaxe bis zum ersten Kill', 'rad', 1),
  ('Kein Fahrzeug', 'rad', 2),
  ('Nur Loot vom Boden', 'rad', 1),
  ('Erste Waffe muss behalten werden', 'rad', 2),
  ('Keine Kisten öffnen', 'rad', 1),
  ('Nur Scharfschützengewehre', 'rad', 1),
  ('Erst 3 Fische fangen, dann looten', 'drop', 1),
  ('Landen ohne Gleiter-Umweg (direkt runter)', 'drop', 2),
  ('Erste gefundene Waffe ist die einzige', 'drop', 2),
  ('Bis zur zweiten Zone im POI bleiben', 'drop', 1),
  ('Keine Heilung bis zum ersten Kill', 'drop', 1);

-- Lootpool der aktuellen Season (Quelle: supabase/loot/aktuelle-season.txt, im Admin per Import pflegbar)
insert into public.loot_items (name, rarity, type, season_id)
select v.name, v.rarity, v.type, (select id from public.seasons where is_current)
from (values
  ('Assault Rifle', 'grau', 'waffe'),
  ('Assault Rifle', 'gruen', 'waffe'),
  ('Assault Rifle', 'blau', 'waffe'),
  ('Assault Rifle', 'lila', 'waffe'),
  ('Assault Rifle', 'gold', 'waffe'),
  ('Heavy Assault Rifle', 'grau', 'waffe'),
  ('Heavy Assault Rifle', 'gruen', 'waffe'),
  ('Heavy Assault Rifle', 'blau', 'waffe'),
  ('Heavy Assault Rifle', 'lila', 'waffe'),
  ('Heavy Assault Rifle', 'gold', 'waffe'),
  ('8-Bit Shotgun', 'grau', 'waffe'),
  ('8-Bit Shotgun', 'gruen', 'waffe'),
  ('8-Bit Shotgun', 'blau', 'waffe'),
  ('8-Bit Shotgun', 'lila', 'waffe'),
  ('8-Bit Shotgun', 'gold', 'waffe'),
  ('Pump Shotgun', 'grau', 'waffe'),
  ('Pump Shotgun', 'gruen', 'waffe'),
  ('Pump Shotgun', 'blau', 'waffe'),
  ('Pump Shotgun', 'lila', 'waffe'),
  ('Pump Shotgun', 'gold', 'waffe'),
  ('Sweeper Shotgun', 'grau', 'waffe'),
  ('Sweeper Shotgun', 'gruen', 'waffe'),
  ('Sweeper Shotgun', 'blau', 'waffe'),
  ('Sweeper Shotgun', 'lila', 'waffe'),
  ('Sweeper Shotgun', 'gold', 'waffe'),
  ('Wood Stake Shotgun', 'blau', 'waffe'),
  ('Wood Stake Shotgun', 'lila', 'waffe'),
  ('Wood Stake Shotgun', 'gold', 'waffe'),
  ('Bonerattler SMG', 'gruen', 'waffe'),
  ('Bonerattler SMG', 'blau', 'waffe'),
  ('Bonerattler SMG', 'lila', 'waffe'),
  ('Bonerattler SMG', 'gold', 'waffe'),
  ('Tactical Pistol', 'grau', 'waffe'),
  ('Tactical Pistol', 'gruen', 'waffe'),
  ('Tactical Pistol', 'blau', 'waffe'),
  ('Tactical Pistol', 'lila', 'waffe'),
  ('Tactical Pistol', 'gold', 'waffe'),
  ('Rebecca''s Guns', 'grau', 'waffe'),
  ('Rebecca''s Guns', 'gruen', 'waffe'),
  ('Rebecca''s Guns', 'blau', 'waffe'),
  ('Rebecca''s Guns', 'lila', 'waffe'),
  ('Rebecca''s Guns', 'gold', 'waffe'),
  ('Mega Buster', 'blau', 'waffe'),
  ('Firework Flare Gun', 'blau', 'waffe'),
  ('Kingdom Key', 'lila', 'waffe'),
  ('Dual Fiend Hunters', 'grau', 'waffe'),
  ('Dual Fiend Hunters', 'gruen', 'waffe'),
  ('Dual Fiend Hunters', 'blau', 'waffe'),
  ('Dual Fiend Hunters', 'lila', 'waffe'),
  ('Dual Fiend Hunters', 'gold', 'waffe'),
  ('Bandages', 'grau', 'heilung'),
  ('Med Kit', 'gruen', 'heilung'),
  ('Small Shield Potion', 'gruen', 'heilung'),
  ('Small Shield Potion', 'blau', 'heilung'),
  ('Shield Potion', 'blau', 'heilung'),
  ('Chug Jug', 'gold', 'heilung'),
  ('Quack Snacks', 'gold', 'heilung'),
  ('Candy Corn', 'gruen', 'heilung'),
  ('Jelly Bean', 'gruen', 'heilung'),
  ('Hop Drop', 'gruen', 'heilung'),
  ('Slap Candy Corn', 'blau', 'heilung'),
  ('Sea Salt Ice Cream', 'blau', 'heilung'),
  ('Sonic Power Sneakers', 'lila', 'utility'),
  ('Witch Broom', 'lila', 'utility'),
  ('Balloons', 'blau', 'utility'),
  ('Override Grenade', 'blau', 'utility'),
  ('Snack-O''-Lantern Gizmo', 'gruen', 'utility'),
  ('Brick-A-Bunker', 'grau', 'utility'),
  ('Shield Bubble Jr.', 'gruen', 'utility'),
  ('Bush', 'gold', 'utility')
) as v(name, rarity, type);

insert into public.drop_spots (name, season_id, x, y)
select v.name, (select id from public.seasons where is_current), v.x, v.y
from (values
  ('Nordküste', 20, 15), ('Zentrum', 50, 50), ('Westwald', 15, 55),
  ('Ostberge', 82, 40), ('Südhafen', 55, 85), ('Insel im See', 40, 35),
  ('Wüstenstadt', 75, 75), ('Burg', 30, 80)
) as v(name, x, y);

insert into public.bingo_tasks (text) values
  ('Kill mit Pickaxe'), ('Top 10 ohne Schild'), ('Gold-Waffe finden'), ('Fisch fangen'),
  ('Kill aus Fahrzeug'), ('3 Kisten in Folge'), ('Kill mit grauer Waffe'), ('Sniper-Kill über 100 m'),
  ('Victory Royale'), ('Kill ohne zu bauen'), ('In der Zone sterben (fast)'), ('Mythische Waffe'),
  ('Revive eines Mitspielers'), ('Lama gefunden'), ('Kill mit Granate'), ('5 Kills'),
  ('Top 5'), ('Doppel-Kill'), ('Geschenk aus Kiste: Heilung'), ('Erste Landung überlebt'),
  ('Kill mit Raketenwerfer'), ('100 Schaden in einem Schuss'), ('Ohne Heilung Top 15'), ('Emote nach Kill'),
  ('Lagerfeuer genutzt'), ('Vom Bus als Letzter abspringen'), ('Kill aus der Luft'), ('Kill mit Pistole');
